[build]
builder = "nixpacks"
buildCommand = "bun install && bunx prisma generate && bun run build"

[deploy]
startCommand = "bunx prisma db push && mkdir -p $STORAGE_PATH && NODE_ENV=production bun .next/standalone/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
type = "path"
path = "/api/route"
timeout = 30
