import { ComponentTemplate } from '@/types';

export const componentTemplates: ComponentTemplate[] = [
  {
    id: 'div',
    name: 'Container',
    type: 'div',
    icon: 'Square',
    category: 'Layout',
    defaultWidth: 300,
    defaultHeight: 200,
    defaultStyles: {
      backgroundColor: '#ffffff',
      borderRadius: '8px',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: '#e2e8f0',
      padding: '16px',
    },
  },
  {
    id: 'flex',
    name: 'Flex Box',
    type: 'flex',
    icon: 'Columns',
    category: 'Layout',
    defaultWidth: 400,
    defaultHeight: 100,
    defaultStyles: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '12px',
      padding: '16px',
      backgroundColor: '#ffffff',
      borderRadius: '8px',
    },
  },
  {
    id: 'grid',
    name: 'Grid',
    type: 'grid',
    icon: 'LayoutGrid',
    category: 'Layout',
    defaultWidth: 400,
    defaultHeight: 300,
    defaultStyles: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: '12px',
      padding: '16px',
      backgroundColor: '#ffffff',
      borderRadius: '8px',
    },
  },
  {
    id: 'row',
    name: 'Row',
    type: 'row',
    icon: 'AlignHorizontalSpaceAround',
    category: 'Layout',
    defaultWidth: 500,
    defaultHeight: 60,
    defaultStyles: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: '12px',
      padding: '12px',
    },
  },
  {
    id: 'column',
    name: 'Column',
    type: 'column',
    icon: 'AlignVerticalSpaceAround',
    category: 'Layout',
    defaultWidth: 200,
    defaultHeight: 300,
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      gap: '12px',
      padding: '12px',
    },
  },
  {
    id: 'text',
    name: 'Text',
    type: 'text',
    icon: 'Type',
    category: 'Basic',
    defaultWidth: 200,
    defaultHeight: 40,
    defaultStyles: {
      fontSize: '16px',
      fontWeight: '400',
      lineHeight: '1.5',
      color: '#0f172a',
    },
    defaultContent: 'Text block',
  },
  {
    id: 'heading',
    name: 'Heading',
    type: 'text',
    icon: 'Heading',
    category: 'Basic',
    defaultWidth: 300,
    defaultHeight: 48,
    defaultStyles: {
      fontSize: '32px',
      fontWeight: '700',
      lineHeight: '1.2',
      color: '#0f172a',
    },
    defaultContent: 'Heading',
  },
  {
    id: 'button',
    name: 'Button',
    type: 'button',
    icon: 'RectangleHorizontal',
    category: 'Basic',
    defaultWidth: 120,
    defaultHeight: 40,
    defaultStyles: {
      backgroundColor: '#6366f1',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '500',
      borderRadius: '8px',
      padding: '8px 16px',
      textAlign: 'center',
      cursor: 'pointer',
      borderStyle: 'none',
    },
    defaultContent: 'Button',
  },
  {
    id: 'link',
    name: 'Link',
    type: 'link',
    icon: 'Link',
    category: 'Basic',
    defaultWidth: 80,
    defaultHeight: 24,
    defaultStyles: {
      color: '#6366f1',
      fontSize: '14px',
      fontWeight: '500',
      cursor: 'pointer',
    },
    defaultContent: 'Link text',
  },
  {
    id: 'input',
    name: 'Input',
    type: 'input',
    icon: 'TextCursorInput',
    category: 'Form',
    defaultWidth: 240,
    defaultHeight: 40,
    defaultStyles: {
      backgroundColor: '#ffffff',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: '#e2e8f0',
      borderRadius: '8px',
      padding: '8px 12px',
      fontSize: '14px',
      color: '#0f172a',
    },
    defaultContent: '',
    placeholder: 'Enter text...',
  },
  {
    id: 'textarea',
    name: 'Textarea',
    type: 'textarea',
    icon: 'AlignLeft',
    category: 'Form',
    defaultWidth: 300,
    defaultHeight: 100,
    defaultStyles: {
      backgroundColor: '#ffffff',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: '#e2e8f0',
      borderRadius: '8px',
      padding: '12px',
      fontSize: '14px',
      color: '#0f172a',
    },
    defaultContent: '',
    placeholder: 'Enter text...',
  },
  {
    id: 'select',
    name: 'Select',
    type: 'select',
    icon: 'ChevronDown',
    category: 'Form',
    defaultWidth: 200,
    defaultHeight: 40,
    defaultStyles: {
      backgroundColor: '#ffffff',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: '#e2e8f0',
      borderRadius: '8px',
      padding: '8px 12px',
      fontSize: '14px',
      color: '#0f172a',
    },
    defaultContent: 'Select option...',
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    type: 'checkbox',
    icon: 'CheckSquare',
    category: 'Form',
    defaultWidth: 20,
    defaultHeight: 20,
    defaultStyles: {
      borderStyle: 'solid',
      borderWidth: '2px',
      borderColor: '#6366f1',
      borderRadius: '4px',
      backgroundColor: '#ffffff',
    },
  },
  {
    id: 'toggle',
    name: 'Toggle',
    type: 'toggle',
    icon: 'ToggleLeft',
    category: 'Form',
    defaultWidth: 44,
    defaultHeight: 24,
    defaultStyles: {
      borderRadius: '12px',
      backgroundColor: '#e2e8f0',
      cursor: 'pointer',
    },
  },
  {
    id: 'image',
    name: 'Image',
    type: 'image',
    icon: 'Image',
    category: 'Media',
    defaultWidth: 300,
    defaultHeight: 200,
    defaultStyles: {
      borderRadius: '8px',
      objectFit: 'cover',
      backgroundColor: '#f1f5f9',
      backgroundSize: 'cover',
    },
    defaultContent: '',
  },
  {
    id: 'avatar',
    name: 'Avatar',
    type: 'avatar',
    icon: 'User',
    category: 'Media',
    defaultWidth: 40,
    defaultHeight: 40,
    defaultStyles: {
      borderRadius: '9999px',
      backgroundColor: '#6366f1',
      objectFit: 'cover',
    },
  },
  {
    id: 'card',
    name: 'Card',
    type: 'card',
    icon: 'CreditCard',
    category: 'Composite',
    defaultWidth: 320,
    defaultHeight: 240,
    defaultStyles: {
      backgroundColor: '#ffffff',
      borderRadius: '12px',
      borderStyle: 'solid',
      borderWidth: '1px',
      borderColor: '#e2e8f0',
      padding: '24px',
      boxShadow: '0 1px 2px 0 rgba(0,0,0,0.05)',
    },
  },
  {
    id: 'navbar',
    name: 'Navbar',
    type: 'navbar',
    icon: 'Menu',
    category: 'Composite',
    defaultWidth: 800,
    defaultHeight: 64,
    defaultStyles: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 24px',
      backgroundColor: '#ffffff',
      borderWidth: '0 0 1px 0',
      borderStyle: 'solid',
      borderColor: '#e2e8f0',
    },
    defaultContent: 'Brand',
  },
  {
    id: 'hero',
    name: 'Hero Section',
    type: 'hero',
    icon: 'Sparkles',
    category: 'Composite',
    defaultWidth: 800,
    defaultHeight: 400,
    defaultStyles: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: '16px',
      padding: '48px',
      backgroundColor: '#f8fafc',
      textAlign: 'center',
    },
    defaultContent: 'Hero Title',
  },
  {
    id: 'badge',
    name: 'Badge',
    type: 'badge',
    icon: 'Tag',
    category: 'Basic',
    defaultWidth: 60,
    defaultHeight: 24,
    defaultStyles: {
      backgroundColor: '#ede9fe',
      color: '#6366f1',
      fontSize: '12px',
      fontWeight: '500',
      borderRadius: '9999px',
      padding: '4px 10px',
      textAlign: 'center',
    },
    defaultContent: 'Badge',
  },
  {
    id: 'separator',
    name: 'Separator',
    type: 'separator',
    icon: 'Minus',
    category: 'Basic',
    defaultWidth: 300,
    defaultHeight: 1,
    defaultStyles: {
      backgroundColor: '#e2e8f0',
    },
  },
  {
    id: 'icon',
    name: 'Icon',
    type: 'icon',
    icon: 'Star',
    category: 'Basic',
    defaultWidth: 24,
    defaultHeight: 24,
    defaultStyles: {
      color: '#0f172a',
      fontSize: '24px',
    },
    defaultContent: '★',
  },
];

export const categories = ['Layout', 'Basic', 'Form', 'Media', 'Composite'];
